<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>ExportKing</RootNamespace>
    <AssemblyName>ExportKing</AssemblyName>
    <DefaultItemExcludes>$(DefaultItemExcludes);ExportKing.Tests/**/*</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.4.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ExportKing.Tests" />
  </ItemGroup>

</Project>
